# Generated by Django 3.0.6 on 2020-06-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificacapg',
            name='descricao',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='classificacapg',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
