# Generated by Django 3.0.6 on 2020-06-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_auto_20200607_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificaPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
                ('descricao', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
