# Generated by Django 3.0.6 on 2020-06-09 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_auto_20200608_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas_pagar',
            name='classificacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.ClassificaPagamento'),
        ),
    ]
