# Generated by Django 3.0.6 on 2020-06-10 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_auto_20200609_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas_receber',
            name='classificacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.ClassificacaRec'),
        ),
    ]
