# Generated by Django 3.0.6 on 2020-06-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_auto_20200609_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas_pagar',
            name='situacao',
            field=models.CharField(default='aberto', max_length=200),
        ),
        migrations.AlterField(
            model_name='contas_receber',
            name='situacao',
            field=models.CharField(default='aberto', max_length=200),
        ),
    ]
